### PR TITLE
Support for single integer size values for square thumbnails

### PR DESCRIPTION
**Pull request by bostrt**

### CODE REVIEW

**Comment by silentsokolov** [comment]
Maybe add and `tuple`?)

```python
(100, 100)
```

**Comment by bostrt** [comment]
Do you mean for `parse_size` to accept a tuple?

**Comment by silentsokolov** [comment]
Yes, or is it superfluous in your opinion?

**Comment by bostrt** [comment]
I think it would be a good addition to this feature. I'll work on it some in my evening and update this pull-request.

**Comment by bostrt** [comment]
`AssertionError: u'2x0x0xxx2x0x0' != u'200x200'`

Looks like I forgot to run the tests in python2 on my side. I'll fix it soon.

**Comment by silentsokolov** [comment]
I think, best way:

```python
try:
    thumbnail_size = [int(x) for x in size.lower().split('x', 1)]
except ValueError:
    raise ValueError('Bad format aka **x**')
```

**Comment by silentsokolov** [comment]
Big thanks!

**Pull request merged**
