### PR TITLE
Code refresh and support for image format

### PR DESCRIPTION
**Pull request by xen**
I am working on an article for the https://www.pylot.me/ and want to use thing extension. And found that `THUMBNAIL_DEFAUL_FORMAT` is not respected. And previews are always in source format. I fixed it here and made overall code refresh and some small refactorings.

### CODE REVIEW

**Comment by xen** [comment]
Also, THUMBNAIL_DEFAUL_FORMAT -> THUMBNAIL_DEFAULT_FORMAT.

**Comment by silentsokolov** [comment]
Thanks!
I think, first need to fix tests (and remove 2.7).
I'm going to add linters later and before that please disable format quotes (option `--skip-string-normalization` if you use `black`)

**Comment by xen** [comment]
@silentsokolov Sorry, Dmitry. I can't support my patch further on the level you probably expect. 

During my research I found your project and read its code. And found several places to improve, typos in configuration and discrepancy with documentation. Also, I took some inspiration from your code and made these quick and definitely dirty and inaccurate changes. 

Actually, we need more control of the future improvements for our code and I wrote a similar part from scratch. So, we don't actually use Flask-Thumbnails in dependency or any other ways. 

I can't guarantee that I will have time in the foreseeable future to make the changes you ask. 

If you find that the cost to merge this patch is too big for you, please close merge request.

With best regards, Mikhail

**Comment by silentsokolov** [comment]
Thank you for your work and for pointing out bugs we will try to fix them!

**Pull request closed without merging**
